# Taking a look at our On Ice data #

Here we will take a quick look at the player metrics collected

In [98]:
import pandas as pd
import numpy as np
from per_60_functions import per_60_to_totals, per_60_to_GP
import os

In [99]:
# Load bio data from directory "../../Data/NHL_PlayerData_NatrualStatTrick/oi" using pandas dataframe

directory = "../../Data/NHL_PlayerData_NaturalStatTrick/oi"

oi_df = pd.DataFrame()

for year in range(2007, 2025):
    filename = f'regSeason_allStrengths_allScores_oi_{year}.csv'
    df = pd.read_csv(f'{directory}/{filename}')
    # Concatenate dataframes with bio_df
    oi_df = pd.concat([oi_df, df])

oi_df.head(-5)

,Year,Player,Team,Position,GP,TOI,TOI/GP,CF/60,CA/60,CF%,...,PDO,Off. Zone Starts/60,Neu. Zone Starts/60,Def. Zone Starts/60,On The Fly Starts/60,Off. Zone Start %,Off. Zone Faceoffs/60,Neu. Zone Faceoffs/60,Def. Zone Faceoffs/60,Off. Zone Faceoff %
0,2007,Aaron Downey,DET,R,56,256.933333,4.588095,45.77,44.60,50.65,...,0.991,18.21,12.14,2.34,65.62,88.64,24.29,15.65,5.14,82.54
1,2007,Aaron Johnson,NYI,D,30,415.850000,13.861667,53.38,50.35,51.46,...,1.02,7.79,11.54,4.04,50.21,65.85,16.59,20.92,13.13,55.83
2,2007,Aaron Miller,VAN,D,57,988.183333,17.336550,38.80,57.99,40.09,...,1.0,4.37,11.72,9.96,53.43,30.51,9.71,18.58,18.09,34.93
3,2007,Aaron Rome,CBJ,D,17,309.033333,18.178431,43.30,46.60,48.16,...,0.944,5.63,11.65,8.54,53.20,39.73,11.26,18.83,15.92,41.43
4,2007,Aaron Voros,MIN,L,55,504.600000,9.174545,49.11,51.37,48.88,...,1.013,13.67,18.07,8.44,59.10,61.83,18.79,24.38,17.12,52.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,2024,Zach Dean,STL,C,1,8.683333,8.683333,0.00,62.19,0.0,...,1.00,6.91,13.82,0.00,55.28,100.00,6.91,13.82,0.00,100.00
877,2024,Zach Hyman,EDM,L,66,1292.750000,19.587121,84.98,45.99,64.88,...,1.025,15.04,9.98,5.62,31.75,72.81,30.82,14.06,13.37,69.75
878,2024,Zach Parise,COL,L,17,234.533333,13.796078,57.05,68.56,45.42,...,0.978,8.44,12.28,11.77,53.72,41.77,13.81,17.65,22.77,37.76
879,2024,Zach Sanford,"ARI, CHI",L,29,314.266667,10.836782,55.18,59.76,48.01,...,1.009,9.55,12.22,5.35,50.21,64.10,17.95,15.66,12.98,58.02
880,2024,Zach Werenski,CBJ,D,57,1389.816667,24.382749,72.57,64.37,52.99,...,0.993,10.79,9.93,7.68,33.03,58.41,27.37,16.49,16.84,61.91

## The importance of our On Ice Data ##

This data is likely to be composed of very valuable features we will likely want to use for training our model, so we should do a fairly thorough job of cleaning and ensuring it is ready for proper analysis.

This data is composed of what are called "advanced metrics".

In [100]:
oi_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16113 entries, 0 to 885
Data columns (total 55 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   16113 non-null  int64
 1   Player                 16113 non-null  object
 2   Team                   16113 non-null  object
 3   Position               16113 non-null  object
 4   GP                     16113 non-null  int64
 5   TOI                    16113 non-null  float64
 6   TOI/GP                 16113 non-null  float64
 7   CF/60                  16113 non-null  float64
 8   CA/60                  16113 non-null  float64
 9   CF%                    16113 non-null  object
 10  FF/60                  16113 non-null  float64
 11  FA/60                  16113 non-null  float64
 12  FF%                    16113 non-null  object
 13  SF/60                  16113 non-null  float64
 14  SA/60                  16113 non-null  float64
 15  SF%                    16113 non-null  object
 16  GF/60                  16113 non-null  float64
 17  GA/60                  16113 non-null  float64
 18  GF%                    16113 non-null  object
 19  xGF/60                 16113 non-null  float64
 20  xGA/60                 16113 non-null  float64
 21  xGF%                   16113 non-null  object
 22  SCF/60                 16113 non-null  float64
 23  SCA/60                 16113 non-null  float64
 24  SCF%                   16113 non-null  object
 25  HDCF/60                16113 non-null  float64
 26  HDCA/60                16113 non-null  float64
 27  HDCF%                  16113 non-null  object
 28  HDGF/60                16113 non-null  float64
 29  HDGA/60                16113 non-null  float64
 30  HDGF%                  16113 non-null  object
 31  MDCF/60                16113 non-null  float64
 32  MDCA/60                16113 non-null  float64
 33  MDCF%                  16113 non-null  object
 34  MDGF/60                16113 non-null  float64
 35  MDGA/60                16113 non-null  float64
 36  MDGF%                  16113 non-null  object
 37  LDCF/60                16113 non-null  float64
 38  LDCA/60                16113 non-null  float64
 39  LDCF%                  16113 non-null  object
 40  LDGF/60                16113 non-null  float64
 41  LDGA/60                16113 non-null  float64
 42  LDGF%                  16113 non-null  object
 43  On-Ice SH%             16113 non-null  object
 44  On-Ice SV%             16113 non-null  object
 45  PDO                    16113 non-null  object
 46  Off. Zone Starts/60    16113 non-null  float64
 47  Neu. Zone Starts/60    16113 non-null  float64
 48  Def. Zone Starts/60    16113 non-null  float64
 49  On The Fly Starts/60   16113 non-null  float64
 50  Off. Zone Start %      16113 non-null  object
 51  Off. Zone Faceoffs/60  16113 non-null  float64
 52  Neu. Zone Faceoffs/60  16113 non-null  float64
 53  Def. Zone Faceoffs/60  16113 non-null  float64
 54  Off. Zone Faceoff %    16113 non-null  object
dtypes: float64(33), int64(2), object(20)
memory usage: 6.9+ MB

Here we see that given 15227 rows, not a single column has a null entry, which is fantastic.

In [101]:
# Use .describe() to get summary statistics of the data in a way that we view all columns

oi_df.describe()

,Year,GP,TOI,TOI/GP,CF/60,CA/60,FF/60,FA/60,SF/60,SA/60,...,LDCA/60,LDGF/60,LDGA/60,Off. Zone Starts/60,Neu. Zone Starts/60,Def. Zone Starts/60,On The Fly Starts/60,Off. Zone Faceoffs/60,Neu. Zone Faceoffs/60,Def. Zone Faceoffs/60
count,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,...,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000,16113.000000
mean,2015.604419,47.177807,778.430285,14.982490,53.927255,55.339922,40.188855,41.235117,28.882536,29.689641,...,37.651246,0.623821,0.668877,10.207633,12.808478,9.315112,47.719222,18.545348,18.620042,17.886219
std,5.183898,27.806134,553.378814,4.554586,10.862991,9.659843,8.272385,7.350659,6.228328,5.726489,...,9.411260,0.781456,0.761003,3.881856,3.266758,4.291803,8.950246,6.016696,4.031421,6.084187
min,2007.000000,1.000000,0.750000,0.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2011.000000,20.000000,237.900000,11.667521,46.960000,49.550000,35.020000,37.130000,25.140000,26.680000,...,31.940000,0.260000,0.340000,7.600000,11.160000,6.570000,41.640000,14.470000,16.690000,13.970000
50%,2016.000000,53.000000,784.850000,15.010833,53.760000,54.800000,40.150000,40.860000,28.890000,29.420000,...,36.380000,0.570000,0.610000,9.960000,12.650000,8.720000,47.050000,18.080000,18.570000,17.160000
75%,2020.000000,72.000000,1228.883333,18.246753,61.080000,60.560000,45.590000,44.900000,32.880000,32.300000,...,41.850000,0.870000,0.860000,12.560000,14.220000,11.560000,52.880000,22.430000,20.380000,21.280000
max,2024.000000,85.000000,2411.950000,29.414024,141.390000,193.720000,135.850000,129.150000,101.890000,128.570000,...,148.570000,60.470000,20.550000,60.000000,80.000000,45.300000,153.190000,81.570000,160.000000,62.620000

# Converting Rates to Totals

The features of our data are all in rate form, and it occurs to me that it may be useful to utilize the totals for our features, instead of the rates. Here I will convert all features that are in a rate format "feature/60" back to simply "feature".

Something convenient that I noticed is that TOI is already in the correct format. As opposed to minutes:seconds it has already been converted to total minutes

In [102]:
per_60_columns = oi_df.filter(like='/60').columns

totals_df = per_60_to_totals(oi_df, per_60_columns)

# Merge oi_df with new_df on axis = 1
oi_df = pd.concat([oi_df, totals_df], axis=1)

In [103]:
gp_df = per_60_to_GP(oi_df, per_60_columns)

oi_df = pd.concat([oi_df, gp_df], axis=1)

In [104]:
# Extract all columns that end in '/60'

per_60_columns = oi_df.filter(like='/60')

per_GP_columns = oi_df.filter(like='/GP')

percentage_columns = oi_df.filter(like='%')

# Extract all columns that are not per 60 or per GP

non_per_columns = oi_df.drop(per_60_columns.columns, axis=1).drop(per_GP_columns.columns, axis=1).drop(percentage_columns.columns, axis=1)

final_data = pd.concat([non_per_columns, per_GP_columns, per_60_columns, percentage_columns], axis=1)
final_data.columns.tolist()

['Year',
 'Player',
 'Team',
 'Position',
 'GP',
 'TOI',
 'PDO',
 'CF',
 'CA',
 'FF',
 'FA',
 'SF',
 'SA',
 'GF',
 'GA',
 'xGF',
 'xGA',
 'SCF',
 'SCA',
 'HDCF',
 'HDCA',
 'HDGF',
 'HDGA',
 'MDCF',
 'MDCA',
 'MDGF',
 'MDGA',
 'LDCF',
 'LDCA',
 'LDGF',
 'LDGA',
 'Off.\xa0Zone Starts',
 'Neu.\xa0Zone Starts',
 'Def.\xa0Zone Starts',
 'On\xa0The\xa0Fly Starts',
 'Off.\xa0Zone Faceoffs',
 'Neu.\xa0Zone Faceoffs',
 'Def.\xa0Zone Faceoffs',
 'TOI/GP',
 'CF/GP',
 'CA/GP',
 'FF/GP',
 'FA/GP',
 'SF/GP',
 'SA/GP',
 'GF/GP',
 'GA/GP',
 'xGF/GP',
 'xGA/GP',
 'SCF/GP',
 'SCA/GP',
 'HDCF/GP',
 'HDCA/GP',
 'HDGF/GP',
 'HDGA/GP',
 'MDCF/GP',
 'MDCA/GP',
 'MDGF/GP',
 'MDGA/GP',
 'LDCF/GP',
 'LDCA/GP',
 'LDGF/GP',
 'LDGA/GP',
 'Off.\xa0Zone Starts/GP',
 'Neu.\xa0Zone Starts/GP',
 'Def.\xa0Zone Starts/GP',
 'On\xa0The\xa0Fly Starts/GP',
 'Off.\xa0Zone Faceoffs/GP',
 'Neu.\xa0Zone Faceoffs/GP',
 'Def.\xa0Zone Faceoffs/GP',
 'CF/60',
 'CA/60',
 'FF/60',
 'FA/60',
 'SF/60',
 'SA/60',
 'GF/60',
 'GA/60',
 'xGF/60',
 'xGA/60',
 'SCF/60',
 'SCA/60',
 'HDCF/60',
 'HDCA/60',
 'HDGF/60',
 'HDGA/60',
 'MDCF/60',
 'MDCA/60',
 'MDGF/60',
 'MDGA/60',
 'LDCF/60',
 'LDCA/60',
 'LDGF/60',
 'LDGA/60',
 'Off.\xa0Zone Starts/60',
 'Neu.\xa0Zone Starts/60',
 'Def.\xa0Zone Starts/60',
 'On\xa0The\xa0Fly Starts/60',
 'Off.\xa0Zone Faceoffs/60',
 'Neu.\xa0Zone Faceoffs/60',
 'Def.\xa0Zone Faceoffs/60',
 'CF%',
 'FF%',
 'SF%',
 'GF%',
 'xGF%',
 'SCF%',
 'HDCF%',
 'HDGF%',
 'MDCF%',
 'MDGF%',
 'LDCF%',
 'LDGF%',
 'On-Ice SH%',
 'On-Ice SV%',
 'Off.\xa0Zone Start %',
 'Off.\xa0Zone Faceoff %']

# Save this data to disk

In [105]:
dir_path = '../../Data/Warehouse/PlayerData/'
filename = 'oi.csv'

if not os.path.exists(dir_path):
    os.makedirs(dir_path)

final_data.to_csv(f'{dir_path}/{filename}', index=False)