# General EDA of our merged Data

In [47]:
import pandas as pd
import numpy as np
import dataprep as dp
from dataprep.eda import plot
import os

# Load in our data
filepath = '../../Data/entitiesResolved/merged_data.csv'
data = pd.read_csv(filepath)

data.head(-5)

/var/folders/h2/kmbhyjx55j5c34gh2d52qthc0000gn/T/ipykernel_10352/3990006058.py:9: DtypeWarning: Columns (37,40,49,67) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(filepath)

,POSITION,PLAYER,TEAM_x,TOI,GP,TOI/GP,GOALS/60,TOTAL ASSISTS/60,FIRST ASSISTS/60,SECOND ASSISTS/60,...,EXP. YEAR,CAP HIT,AAV,SALARY,BASE SALARY,S.BONUS,P.BONUS,SEASON,Y_SALARY_CAP,Y_SALARY_CAP_PERCENTAGE
0,r,adam burish,chi,951.616667,81,11.748354,0.25,0.25,0.19,0.06,...,2008,"$575,000","$575,000","$575,000","$500,000","$75,000",$0,2007-08,50300000,0.011431
1,d,adam foote,"cbj, col",1754.250000,75,23.390000,0.03,0.51,0.10,0.41,...,2008,"$4,600,000","$4,600,000","$4,600,000","$4,600,000",$0,$0,2007-08,50300000,0.091451
2,r,adam hall,pit,546.150000,46,11.872826,0.22,0.44,0.11,0.33,...,2008,"$525,000","$525,000","$525,000","$525,000",$0,$0,2007-08,50300000,0.010437
3,r,ales hemsky,edm,1374.483333,74,18.574099,0.87,2.23,1.57,0.65,...,2012,"$4,100,000","$4,100,000","$3,600,000","$3,600,000",$0,$0,2007-08,50300000,0.081511
4,r,ales kotalik,buf,1212.050000,79,15.342405,1.14,0.99,0.35,0.64,...,2009,"$2,333,333","$2,333,333","$2,500,000","$2,500,000",$0,$0,2007-08,50300000,0.046388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12947,c,zach aston-reese,det,6.350000,1,6.350000,0.00,0.00,0.00,0.00,...,2024,"$775,000","$775,000","$775,000","$775,000",$0,$0,2023-24,83500000,0.009281
12948,l,zach benson,buf,876.383333,60,14.606389,0.62,0.96,0.55,0.41,...,2026,"$950,000","$1,600,000","$950,000","$855,000","$95,000","$650,000",2023-24,83500000,0.011377
12949,d,zach bogosian,"min, t.b",964.033333,55,17.527879,0.19,0.56,0.25,0.31,...,2024,"$850,000","$850,000","$1,050,000","$1,050,000",$0,$0,2023-24,83500000,0.010180
12950,c,zach dean,stl,8.683333,1,8.683333,0.00,0.00,0.00,0.00,...,2026,"$852,500","$863,333","$892,500","$800,000","$92,500","$32,500",2023-24,83500000,0.010210
12951,l,zach hyman,edm,1292.750000,66,19.587121,2.23,0.88,0.46,0.42,...,2028,"$5,500,000","$5,500,000","$7,650,000","$7,650,000",$0,$0,2023-24,83500000,0.065868

In [48]:
data.columns.to_list()

['POSITION',
 'PLAYER',
 'TEAM_x',
 'TOI',
 'GP',
 'TOI/GP',
 'GOALS/60',
 'TOTAL ASSISTS/60',
 'FIRST ASSISTS/60',
 'SECOND ASSISTS/60',
 'TOTAL POINTS/60',
 'IPP',
 'SHOTS/60',
 'SH%',
 'IXG/60',
 'ICF/60',
 'IFF/60',
 'ISCF/60',
 'IHDCF/60',
 'RUSH ATTEMPTS/60',
 'REBOUNDS CREATED/60',
 'PIM/60',
 'TOTAL PENALTIES/60',
 'MINOR/60',
 'MAJOR/60',
 'MISCONDUCT/60',
 'PENALTIES DRAWN/60',
 'GIVEAWAYS/60',
 'TAKEAWAYS/60',
 'HITS/60',
 'HITS TAKEN/60',
 'SHOTS BLOCKED/60',
 'FACEOFFS WON/60',
 'FACEOFFS LOST/60',
 'FACEOFFS %',
 'CF/60',
 'CA/60',
 'CF%',
 'FF/60',
 'FA/60',
 'FF%',
 'SF/60',
 'SA/60',
 'SF%',
 'GF/60',
 'GA/60',
 'GF%',
 'XGF/60',
 'XGA/60',
 'XGF%',
 'SCF/60',
 'SCA/60',
 'SCF%',
 'HDCF/60',
 'HDCA/60',
 'HDCF%',
 'HDGF/60',
 'HDGA/60',
 'HDGF%',
 'MDCF/60',
 'MDCA/60',
 'MDCF%',
 'MDGF/60',
 'MDGA/60',
 'MDGF%',
 'LDCF/60',
 'LDCA/60',
 'LDCF%',
 'LDGF/60',
 'LDGA/60',
 'LDGF%',
 'ON-ICE SH%',
 'ON-ICE SV%',
 'PDO',
 'OFF.\xa0ZONE STARTS/60',
 'NEU.\xa0ZONE STARTS/60',
 'DEF.\xa0ZONE STARTS/60',
 'ON\xa0THE\xa0FLY STARTS/60',
 'OFF.\xa0ZONE START %',
 'OFF.\xa0ZONE FACEOFFS/60',
 'NEU.\xa0ZONE FACEOFFS/60',
 'DEF.\xa0ZONE FACEOFFS/60',
 'OFF.\xa0ZONE FACEOFF %',
 'AGE_x',
 'DATE OF BIRTH',
 'BIRTH CITY',
 'BIRTH STATE/PROVINCE',
 'BIRTH COUNTRY',
 'NATIONALITY',
 'HEIGHT (IN)',
 'WEIGHT (LBS)',
 'DRAFT YEAR',
 'DRAFT TEAM',
 'DRAFT ROUND',
 'ROUND PICK',
 'OVERALL DRAFT POSITION',
 'YEAR',
 'TEAM_y',
 'AGE_y',
 'COUNTRY',
 'POS',
 'HANDED',
 'DRAFTED',
 'SIGNING TEAM',
 'TYPE',
 'SIGNING AGE',
 'CLAUSE',
 'LENGTH',
 'EXPIRY',
 'EXP. YEAR',
 'CAP HIT',
 'AAV',
 'SALARY',
 'BASE SALARY',
 'S.BONUS',
 'P.BONUS',
 'SEASON',
 'Y_SALARY_CAP',
 'Y_SALARY_CAP_PERCENTAGE']

Notice that we have a few similar column names: TEAM and AGE that are still overlapping from our merge. We should decide which of these to keep. 

## First, lets take a look at TEAM

In [49]:
print(data['TEAM_x'].unique())
print(data['TEAM_x'].nunique())
print(data['TEAM_y'].unique())
print(data['TEAM_y'].nunique())

['chi' 'cbj, col' 'pit' 'edm' 'buf' 'wsh' 'cgy' 'van' 'nsh' 'tor' 'atl'
 'det' 'mtl' 'ott' 'bos' 'ana' 'car, chi' 'n.j' 'nyi' 'ana, stl' 'l.a'
 'dal' 'stl' 'chi, phi' 'min' 't.b' 'dal, t.b' 'col' 'det, l.a' 'nyr'
 'phi' 'fla' 'buf, s.j' 'n.j, stl' 'nyr, stl' 's.j' 'atl, pit' 'cbj, edm'
 'phx' 'car' 'cbj' 'min, tor' 'pit, tor' 'cgy, chi, phi' 'car, ott'
 'col, fla' 'ana, nyi' 'van, wsh' 'cbj, wsh' 'ana, bos' 'dal, min'
 'buf, edm' 'stl, tor' 'cbj, ott' 'dal, stl' 'nyi, pit' 'ana, dal'
 'nyi, ott' 'cbj, t.b' 'ana, pit' 'min, nyr' 'phi, phx' 'dal, pit'
 'nyr, phx' 'buf, tor' 'dal, mtl' 'ana, atl' 'car, edm' 'mtl, phi'
 'ana, chi' 'atl, cbj' 'car, t.b' 'car, l.a' 'col, van' 'bos, t.b'
 'atl, mtl' 'cgy, phx' 'ana, van' 'fla, nsh' 'fla, t.b' 'edm, l.a'
 'dal, nyr' 't.b, van' 'fla, phi, t.b' 'ana, s.j' 'cgy, edm' 'ana, car'
 'cgy, nyr' 'car, van' 'ana, chi, min' 'min, mtl' 'car, wsh' 'bos, fla'
 'chi, min' 'bos, min' 'atl, buf' 'bos, buf' 'edm, nsh' 'bos, phx'
 'cgy, tor' 'fla, mtl' 'det, t.b' 'cgy, nsh' 'min, wsh' 'ana, nyr'
 'cbj, l.a' 'atl, n.j' 'ana, tor' 'l.a, t.b' 'car, tor' 'nyr, s.j'
 'col, phx' 'ana, mtl' 'phx, tor' 'ana, edm' 'phi, t.b' 'phx, van'
 'mtl, stl' 'nyi, t.b' 'car, s.j' 'ana, phx' 'buf, cbj' 'car, col'
 'det, phi' 'car, cgy' 'atl, s.j' 'atl, bos' 'buf, stl' 'ana, cgy'
 'car, fla' 'fla, nyr' 'chi, ott' 'fla, van' 'bos, ott' 'col, stl'
 'n.j, wsh' 'fla, wsh' 'stl, t.b' 'atl, cgy' 'car, cgy, s.j' 'chi, fla'
 'mtl, nyi' 'dal, n.j' 'ana, ott' 'phi, tor' 'nsh, ott' 'bos, col'
 'ana, mtl, van' 'atl, fla' 'car, min' 'atl, nyi' 'cbj, phx'
 'ana, car, fla' 'col, mtl' 'col, wsh' 'col, edm' 'bos, tor' 'wpg'
 'car, n.j' 'mtl, nsh' 'ana, wpg' 'cgy, nyi' 'ott, t.b' 'bos, nyi'
 'nsh, phx, pit' 'buf, van' 'cbj, min' 'col, s.j' 'ott, phx' 's.j, t.b'
 'cbj, wpg' 'car, mtl' 'chi, wpg' 'cbj, stl' 'dal, fla' 'ana, min, n.j'
 'col, det' 'min, n.j' 'cbj, pit' 'cgy, mtl' 'edm, min' 'dal, phi'
 'buf, nsh' 'fla, n.j' 'cbj, van' 'col, t.b' 'edm, stl' 'car, phi, t.b'
 'n.j, wpg' 'cbj, cgy' 'n.j, nsh' 'l.a, mtl' 'dal, van' 'cbj, nyr'
 'pit, s.j' 'pit, wpg' 's.j, tor' 'cgy, pit' 'buf, min' 'cgy, stl'
 'mtl, nyr' 'edm, fla' 'car, pit' 'fla, l.a' 'bos, dal' 'nsh, wsh'
 'chi, s.j' 'edm, tor' 'fla, wpg' 'phx, s.j' 'buf, l.a' 'col, tor'
 'nsh, s.j' 'l.a, phi' 'n.j, phx' 'phi, van' 'col, dal' 'bos, stl'
 'car, nsh, pit' 'edm, ott' 'bos, phi' 'nyi, phi' 'phx, wsh' 'bos, edm'
 'buf, ott' 'mtl, van' 'l.a, nyr' 'det, nsh' 'chi, phx' 'ana, wsh'
 'nsh, nyr' 'cgy, dal' 'fla, pit' 'nyr, t.b' 'buf, pit' 'buf, min, nyi'
 'chi, t.b' 'edm, s.j' 'chi, nyi' 'mtl, nyr, van' 'col, phi'
 'buf, mtl, nyi' 'chi, van' 'ari' 'car, det' 'ari, chi' 'ari, van'
 'dal, s.j' 'buf, mtl' 'ari, nyr' 'nsh, tor' 'ana, fla' 'ari, bos'
 'cgy, wsh' 'cbj, tor' 'edm, pit' 'ari, cgy, dal' 'buf, wpg'
 'ana, t.b, tor' 'dal, det' 'pit, stl' 'ana, cbj' 'car, wpg' 'edm, mtl'
 'cbj, chi' 'cbj, dal' 'nyr, wpg' 'det, n.j' 'ari, edm, nsh, pit'
 'nsh, stl, tor' 'ana, cbj, mtl' 'ari, edm, pit' 'fla, min' 'cgy, van'
 'cbj, chi, tor' 'ari, s.j' 'nyi, s.j' 'ari, stl' 'edm, van' 'edm, wpg'
 'ari, col' 'n.j, pit' 'tor, wsh' 'ana, col' 'chi, l.a' 'ari, mtl'
 'ott, tor' 'chi, mtl' 'cgy, min' 'mtl, n.j' 'col, n.j' 'car, nyr'
 'det, fla' 'ana, buf' 'cgy, fla' 'ana, ari, chi' 'bos, car' 'ari, cbj'
 'bos, det' 'bos, n.j' 'mtl, s.j' 'buf, wsh' 'chi, l.a, pit' 'cbj, nsh'
 'ott, stl' 'ari, pit' 'ari, nsh' 'chi, pit' 'ari, wpg' 'ott, van'
 'det, tor' 'nsh, stl' 'det, nyr' 't.b, tor' 'col, nsh' 'cgy, ott'
 'cbj, n.j' 'bos, wpg' 's.j, van' 'col, l.a' 'chi, dal' 'stl, wsh'
 'phi, pit' 'ari, min' 'nyr, ott' 'ari, cgy' 'mtl, t.b' 'ari, tor'
 'n.j, nsh, van' 'fla, tor' 'ana, n.j' 'det, mtl' 'edm, nyr' 'chi, det'
 'ott, s.j' 'car, stl' 'vgk' 'edm, mtl, nyi' 'van, vgk' 'ott, pit'
 'l.a, ott' 'ana, t.b' 'mtl, wpg' 'ott, phi' 'cbj, edm, l.a, van'
 'bos, nyr' 'col, ott' 'n.j, nyr' 'min, stl' 'edm, wsh' 'l.a, van'
 'cgy, l.a, ott' 'edm, n.j' 'stl, wpg' 'det, pit' 's.j, vgk' 'chi, nsh'
 'pit, vgk' 'buf, det, pit' 'ari, l.a' 'mtl, tor' 'det, vgk' 'bos, chi'
 'min, nsh' 'min, vgk' 'chi, edm' 'l.a, pit, wsh' 'edm, fla, ott'
 'col, fla, pit' 'pit, van' 'det, s.j' 'l.a, tor' 'ari, mtl, phi'
 'tor, van' 'det, wsh' 'ott, vgk' 'min, wpg' 'ana, stl, van' 'fla, s.j'
 'cgy, l.a' 'car, nsh' 'nsh, phi' 'edm, nyr, van' 'l.a, pit, van'
 'car, edm, vgk' 'l.a, vgk' 'min, pit' 'det, edm' 'n.j, nyi' 'n.j, t.b'
 'cgy, s.j' 's.j, wsh' 'vgk, wsh' 'vgk, wpg' 'det, ott' 'ana, phi'
 'ott, wpg' 'cgy, chi' 'l.a, mtl, wsh' 'det, stl' 'fla, ott' 'ana, nsh'
 'buf, mtl, stl' 'mtl, ott' 'mtl, vgk' 'tor, wpg' 'ari, n.j'
 'col, nyr, ott' 'buf, n.j' 'buf, t.b' 'buf, fla' 'ari, buf'
 'col, min, s.j' 'col, min' 'bos, nsh' 'l.a, pit' 'van, wpg' 'chi, vgk'
 'phi, wsh' 'mtl, vgk, wpg' 'sea' 'sea, t.b' 'nyi, sea' 'fla, phi'
 'sea, tor' 'sea, wsh' 'edm, phi' 'sea, vgk' 'ari, wsh' 'nyr, phi'
 'bos, sea' 'sea, wpg' 'car, cbj' 'tor, vgk' 'n.j, sea' 'ana, min'
 'buf, vgk' 'ari, t.b, wpg' 'nyr, van' 'min, sea' 'buf, chi' 'chi, col'
 'n.j, s.j' 'nyi, van' 'nsh, t.b' 'bos, wsh' 'n.j, van' 'col, nyr, tor'
 'nsh, sea' 'det, van' 'stl, vgk' 'bos, van' 'nyr, vgk' 'chi, tor'
 'ari, ott' 's.j, sea' 's.j, t.b, wpg' 'nsh, pit' 'ari, edm' 'nsh, wpg'
 'det, min' 'chi, nyr' 'nyi, tor' 'ari, car' 't.b, wpg' 'bos, cbj'
 'chi, nsh, van' 'buf, col' 'cgy, vgk' 'min, s.j' 'nyr, pit' 'mtl, pit'
 'buf, phi' 'ari, t.b' 'pit, wsh' 'fla, nyi' 'cgy, n.j' 'nyi, stl'
 'l.a, nsh' 'col, sea' 'min, t.b']
481
['-' 'min' 'wsh' 'col' 'lak' 'car' 'tbl' 'ari' 'nyi' 'ott' 'edm' 'det'
 'phi' 'pit' 'dal' 'fla' 'bos' 'chi' 'vgk' 'nyr' 'nsh' 'tor' 'cgy' 'sjs'
 'van' 'stl' 'ana' 'buf' 'sea' 'wpg' 'njd' 'mtl' 'cbj']
33

Having 481 different values for TEAM seems unweildy, so lets drop the TEAM_x column and stick with something a bit simpler.

In [50]:
# Assign the values in 'TEAM_y' to 'TEAM_x' and drop the column 'TEAM_y'
data['TEAM_x'] = data['TEAM_y']
data.drop(columns=['TEAM_y'], inplace=True)

# Rename the column 'TEAM_x' to 'TEAM'
data.rename(columns={'TEAM_x': 'TEAM'}, inplace=True)
data.columns.to_list()

['POSITION',
 'PLAYER',
 'TEAM',
 'TOI',
 'GP',
 'TOI/GP',
 'GOALS/60',
 'TOTAL ASSISTS/60',
 'FIRST ASSISTS/60',
 'SECOND ASSISTS/60',
 'TOTAL POINTS/60',
 'IPP',
 'SHOTS/60',
 'SH%',
 'IXG/60',
 'ICF/60',
 'IFF/60',
 'ISCF/60',
 'IHDCF/60',
 'RUSH ATTEMPTS/60',
 'REBOUNDS CREATED/60',
 'PIM/60',
 'TOTAL PENALTIES/60',
 'MINOR/60',
 'MAJOR/60',
 'MISCONDUCT/60',
 'PENALTIES DRAWN/60',
 'GIVEAWAYS/60',
 'TAKEAWAYS/60',
 'HITS/60',
 'HITS TAKEN/60',
 'SHOTS BLOCKED/60',
 'FACEOFFS WON/60',
 'FACEOFFS LOST/60',
 'FACEOFFS %',
 'CF/60',
 'CA/60',
 'CF%',
 'FF/60',
 'FA/60',
 'FF%',
 'SF/60',
 'SA/60',
 'SF%',
 'GF/60',
 'GA/60',
 'GF%',
 'XGF/60',
 'XGA/60',
 'XGF%',
 'SCF/60',
 'SCA/60',
 'SCF%',
 'HDCF/60',
 'HDCA/60',
 'HDCF%',
 'HDGF/60',
 'HDGA/60',
 'HDGF%',
 'MDCF/60',
 'MDCA/60',
 'MDCF%',
 'MDGF/60',
 'MDGA/60',
 'MDGF%',
 'LDCF/60',
 'LDCA/60',
 'LDCF%',
 'LDGF/60',
 'LDGA/60',
 'LDGF%',
 'ON-ICE SH%',
 'ON-ICE SV%',
 'PDO',
 'OFF.\xa0ZONE STARTS/60',
 'NEU.\xa0ZONE STARTS/60',
 'DEF.\xa0ZONE STARTS/60',
 'ON\xa0THE\xa0FLY STARTS/60',
 'OFF.\xa0ZONE START %',
 'OFF.\xa0ZONE FACEOFFS/60',
 'NEU.\xa0ZONE FACEOFFS/60',
 'DEF.\xa0ZONE FACEOFFS/60',
 'OFF.\xa0ZONE FACEOFF %',
 'AGE_x',
 'DATE OF BIRTH',
 'BIRTH CITY',
 'BIRTH STATE/PROVINCE',
 'BIRTH COUNTRY',
 'NATIONALITY',
 'HEIGHT (IN)',
 'WEIGHT (LBS)',
 'DRAFT YEAR',
 'DRAFT TEAM',
 'DRAFT ROUND',
 'ROUND PICK',
 'OVERALL DRAFT POSITION',
 'YEAR',
 'AGE_y',
 'COUNTRY',
 'POS',
 'HANDED',
 'DRAFTED',
 'SIGNING TEAM',
 'TYPE',
 'SIGNING AGE',
 'CLAUSE',
 'LENGTH',
 'EXPIRY',
 'EXP. YEAR',
 'CAP HIT',
 'AAV',
 'SALARY',
 'BASE SALARY',
 'S.BONUS',
 'P.BONUS',
 'SEASON',
 'Y_SALARY_CAP',
 'Y_SALARY_CAP_PERCENTAGE']

# Now we should do the same thing with the AGE columns

In [51]:
print(data['AGE_x'].unique())
print(data['AGE_x'].nunique())
print(data['AGE_y'].unique())
print(data['AGE_y'].nunique())

[41 52 43 40 45 38 44 37 51 48 42 36 46 49 53 47 39 50 35 54 34 55 62 57
 33 32 56 31 30 29 28 27 26 25 24 23 22 21 20 19 18]
41
['24' '35' '26' '23' '28' '21' '27' '20' '34' '31' '29' '32' '25' '19'
 '36' '30' '22' '33' 'Deceased (28)' '37' '18' 'Deceased (37)' '17'
 'Deceased (34)' '38' 'Deceased (36)' '39' '46' '42' 'Deceased (38)'
 'Deceased (35)' '47' '41' '40' 'Deceased (23)' 'Deceased (31)'
 'Deceased (29)' 'Deceased (25)' '43' '44']
40

The values from our AGE_x columns unfortunately do not make a lot of sense, seeing as nobody who is 62 years old has ever played in the NHL. On the other hand,the values in our AGE_y column DO make a lot of sense, as there have been players who play and get paid up until they are in their mid forties, however it is very rare.

## How to proceed?

I think we should make a feature "Deceased" that extracts all rows where 'AGE_y' starts with 'Deceased', then convert 'AGE_y' to numeric, then replace 'AGE_x' with 'AGE_y', then finally rename 'AGE_x' to simply 'AGE'.

In [52]:
# Create a new feature 'DECEASED' and one-hot-encode it
data['DECEASED'] = np.where(data['AGE_y'].str.startswith('Deceased'), 1, 0)

# Print the updated dataframe
print(data['DECEASED'].unique())

[0 1]

In [53]:
# Extract the age from the 'AGE_y' column and convert it to an integer
data['AGE_y'] = data['AGE_y'].str.extract('(\d+)', expand=False).astype(int)

In [54]:
data['AGE_x'] = data['AGE_y']
data.drop(columns=['AGE_y'], inplace=True)
data.rename(columns={'AGE_x': 'AGE'}, inplace=True)

In [55]:
data.columns.to_list()

['POSITION',
 'PLAYER',
 'TEAM',
 'TOI',
 'GP',
 'TOI/GP',
 'GOALS/60',
 'TOTAL ASSISTS/60',
 'FIRST ASSISTS/60',
 'SECOND ASSISTS/60',
 'TOTAL POINTS/60',
 'IPP',
 'SHOTS/60',
 'SH%',
 'IXG/60',
 'ICF/60',
 'IFF/60',
 'ISCF/60',
 'IHDCF/60',
 'RUSH ATTEMPTS/60',
 'REBOUNDS CREATED/60',
 'PIM/60',
 'TOTAL PENALTIES/60',
 'MINOR/60',
 'MAJOR/60',
 'MISCONDUCT/60',
 'PENALTIES DRAWN/60',
 'GIVEAWAYS/60',
 'TAKEAWAYS/60',
 'HITS/60',
 'HITS TAKEN/60',
 'SHOTS BLOCKED/60',
 'FACEOFFS WON/60',
 'FACEOFFS LOST/60',
 'FACEOFFS %',
 'CF/60',
 'CA/60',
 'CF%',
 'FF/60',
 'FA/60',
 'FF%',
 'SF/60',
 'SA/60',
 'SF%',
 'GF/60',
 'GA/60',
 'GF%',
 'XGF/60',
 'XGA/60',
 'XGF%',
 'SCF/60',
 'SCA/60',
 'SCF%',
 'HDCF/60',
 'HDCA/60',
 'HDCF%',
 'HDGF/60',
 'HDGA/60',
 'HDGF%',
 'MDCF/60',
 'MDCA/60',
 'MDCF%',
 'MDGF/60',
 'MDGA/60',
 'MDGF%',
 'LDCF/60',
 'LDCA/60',
 'LDCF%',
 'LDGF/60',
 'LDGA/60',
 'LDGF%',
 'ON-ICE SH%',
 'ON-ICE SV%',
 'PDO',
 'OFF.\xa0ZONE STARTS/60',
 'NEU.\xa0ZONE STARTS/60',
 'DEF.\xa0ZONE STARTS/60',
 'ON\xa0THE\xa0FLY STARTS/60',
 'OFF.\xa0ZONE START %',
 'OFF.\xa0ZONE FACEOFFS/60',
 'NEU.\xa0ZONE FACEOFFS/60',
 'DEF.\xa0ZONE FACEOFFS/60',
 'OFF.\xa0ZONE FACEOFF %',
 'AGE',
 'DATE OF BIRTH',
 'BIRTH CITY',
 'BIRTH STATE/PROVINCE',
 'BIRTH COUNTRY',
 'NATIONALITY',
 'HEIGHT (IN)',
 'WEIGHT (LBS)',
 'DRAFT YEAR',
 'DRAFT TEAM',
 'DRAFT ROUND',
 'ROUND PICK',
 'OVERALL DRAFT POSITION',
 'YEAR',
 'COUNTRY',
 'POS',
 'HANDED',
 'DRAFTED',
 'SIGNING TEAM',
 'TYPE',
 'SIGNING AGE',
 'CLAUSE',
 'LENGTH',
 'EXPIRY',
 'EXP. YEAR',
 'CAP HIT',
 'AAV',
 'SALARY',
 'BASE SALARY',
 'S.BONUS',
 'P.BONUS',
 'SEASON',
 'Y_SALARY_CAP',
 'Y_SALARY_CAP_PERCENTAGE',
 'DECEASED']

In [56]:
# Save the merged data to a csv file
output_dir = '../../Data/entitiesResolved'
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

output_file = output_dir + '/merged_data.csv'
data.to_csv(output_file, index=False)