# Getting the data ready for the Front-End

In [44]:
import pandas as pd
import os

# Load in our data
filepath = '../../Data/Warehouse/MergedData/merged_data_clean.csv'
data = pd.read_csv(filepath)

data.head(-5)

,TEAM,PLAYER,POSITION,GP,TOI/GP,TOI,IPP,GOALS,TOTAL ASSISTS,FIRST ASSISTS,...,CAP HIT,AAV,SALARY,BASE SALARY,S.BONUS,P.BONUS,SEASON,SALARY CAP,SALARY CAP PERCENTAGE,DECEASED
0,chi,adam burish,r,81,11.748354,951.616667,40.00,4,4,3,...,575000,575000,575000,500000,75000,0,2007-08,50300000,0.011431,0
1,pit,adam hall,r,46,11.872826,546.150000,75.00,2,4,1,...,525000,525000,525000,525000,0,0,2007-08,50300000,0.010437,0
2,edm,ales hemsky,r,74,18.574099,1374.483333,81.61,20,51,36,...,4100000,4100000,3600000,3600000,0,0,2007-08,50300000,0.081511,0
3,buf,ales kotalik,r,79,15.342405,1212.050000,67.19,23,20,7,...,2333333,2333333,2500000,2500000,0,0,2007-08,50300000,0.046388,0
4,pit,alex goligoski,d,3,13.938889,41.816667,100.00,0,2,1,...,845300,984200,795300,500000,295300,188900,2007-08,50300000,0.016805,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12139,det,zach aston-reese,c,1,6.350000,6.350000,NaN,0,0,0,...,775000,775000,775000,775000,0,0,2023-24,83500000,0.009281,0
12140,buf,zach benson,l,60,14.606389,876.383333,63.89,9,14,8,...,950000,1600000,950000,855000,95000,650000,2023-24,83500000,0.011377,0
12141,"min, t.b",zach bogosian,d,55,17.527879,964.033333,29.27,3,9,4,...,850000,850000,1050000,1050000,0,0,2023-24,83500000,0.010180,0
12142,stl,zach dean,c,1,8.683333,8.683333,NaN,0,0,0,...,852500,863333,892500,800000,92500,32500,2023-24,83500000,0.010210,0
12143,edm,zach hyman,l,66,19.587121,1292.750000,50.00,48,19,10,...,5500000,5500000,7650000,7650000,0,0,2023-24,83500000,0.065868,0

## Dropping Columns
The model primarily found the /GP rates more useful than the /60 rates, so for simplicity we will drop the /60 columns

In [45]:
# drop all columns from data that end in '/60'
data = data.drop(data.filter(regex='/60').columns, axis=1)

In [46]:
data.columns.tolist()

['TEAM',
 'PLAYER',
 'POSITION',
 'GP',
 'TOI/GP',
 'TOI',
 'IPP',
 'GOALS',
 'TOTAL ASSISTS',
 'FIRST ASSISTS',
 'SECOND ASSISTS',
 'TOTAL POINTS',
 'SHOTS',
 'IXG',
 'ICF',
 'IFF',
 'ISCF',
 'IHDCF',
 'RUSH ATTEMPTS',
 'REBOUNDS CREATED',
 'PIM',
 'TOTAL PENALTIES',
 'MINOR',
 'MAJOR',
 'MISCONDUCT',
 'PENALTIES DRAWN',
 'GIVEAWAYS',
 'TAKEAWAYS',
 'HITS',
 'HITS TAKEN',
 'SHOTS BLOCKED',
 'FACEOFFS WON',
 'FACEOFFS LOST',
 'GOALS/GP',
 'TOTAL ASSISTS/GP',
 'FIRST ASSISTS/GP',
 'SECOND ASSISTS/GP',
 'TOTAL POINTS/GP',
 'SHOTS/GP',
 'IXG/GP',
 'ICF/GP',
 'IFF/GP',
 'ISCF/GP',
 'IHDCF/GP',
 'RUSH ATTEMPTS/GP',
 'REBOUNDS CREATED/GP',
 'PIM/GP',
 'TOTAL PENALTIES/GP',
 'MINOR/GP',
 'MAJOR/GP',
 'MISCONDUCT/GP',
 'PENALTIES DRAWN/GP',
 'GIVEAWAYS/GP',
 'TAKEAWAYS/GP',
 'HITS/GP',
 'HITS TAKEN/GP',
 'SHOTS BLOCKED/GP',
 'FACEOFFS WON/GP',
 'FACEOFFS LOST/GP',
 'SH%',
 'FACEOFFS %',
 'PDO',
 'CF',
 'CA',
 'FF',
 'FA',
 'SF',
 'SA',
 'GF',
 'GA',
 'XGF',
 'XGA',
 'SCF',
 'SCA',
 'HDCF',
 'HDCA',
 'HDGF',
 'HDGA',
 'MDCF',
 'MDCA',
 'MDGF',
 'MDGA',
 'LDCF',
 'LDCA',
 'LDGF',
 'LDGA',
 'OFF.\xa0ZONE STARTS',
 'NEU.\xa0ZONE STARTS',
 'DEF.\xa0ZONE STARTS',
 'ON\xa0THE\xa0FLY STARTS',
 'OFF.\xa0ZONE FACEOFFS',
 'NEU.\xa0ZONE FACEOFFS',
 'DEF.\xa0ZONE FACEOFFS',
 'CF/GP',
 'CA/GP',
 'FF/GP',
 'FA/GP',
 'SF/GP',
 'SA/GP',
 'GF/GP',
 'GA/GP',
 'XGF/GP',
 'XGA/GP',
 'SCF/GP',
 'SCA/GP',
 'HDCF/GP',
 'HDCA/GP',
 'HDGF/GP',
 'HDGA/GP',
 'MDCF/GP',
 'MDCA/GP',
 'MDGF/GP',
 'MDGA/GP',
 'LDCF/GP',
 'LDCA/GP',
 'LDGF/GP',
 'LDGA/GP',
 'OFF.\xa0ZONE STARTS/GP',
 'NEU.\xa0ZONE STARTS/GP',
 'DEF.\xa0ZONE STARTS/GP',
 'ON\xa0THE\xa0FLY STARTS/GP',
 'OFF.\xa0ZONE FACEOFFS/GP',
 'NEU.\xa0ZONE FACEOFFS/GP',
 'DEF.\xa0ZONE FACEOFFS/GP',
 'CF%',
 'FF%',
 'SF%',
 'GF%',
 'XGF%',
 'SCF%',
 'HDCF%',
 'HDGF%',
 'MDCF%',
 'MDGF%',
 'LDCF%',
 'LDGF%',
 'ON-ICE SH%',
 'ON-ICE SV%',
 'OFF.\xa0ZONE START %',
 'OFF.\xa0ZONE FACEOFF %',
 'AGE',
 'DATE OF BIRTH',
 'BIRTH CITY',
 'BIRTH STATE/PROVINCE',
 'BIRTH COUNTRY',
 'NATIONALITY',
 'HEIGHT (IN)',
 'WEIGHT (LBS)',
 'DRAFT YEAR',
 'DRAFT TEAM',
 'DRAFT ROUND',
 'ROUND PICK',
 'OVERALL DRAFT POSITION',
 'COUNTRY',
 'HANDED',
 'DRAFTED',
 'SIGNING TEAM',
 'TYPE',
 'SIGNING AGE',
 'CLAUSE',
 'LENGTH',
 'EXPIRY',
 'EXP. YEAR',
 'CAP HIT',
 'AAV',
 'SALARY',
 'BASE SALARY',
 'S.BONUS',
 'P.BONUS',
 'SEASON',
 'SALARY CAP',
 'SALARY CAP PERCENTAGE',
 'DECEASED']

In [47]:
# Load in the predictions

# Load in our data
defenence_filepath = '../../Data/Warehouse/Predictions/defence_predictions.csv'
forwards_filepath = '../../Data/Warehouse/Predictions/forwards_predictions.csv'

defence_predictions = pd.read_csv(defenence_filepath)
forwards_predictions = pd.read_csv(forwards_filepath)

forwards_predictions.head()

          PLAYER   SEASON     TOI/GP  PRED_SALARY_PERCENTAGE
0    adam burish  2007-08  11.748354                0.014010
1      adam hall  2007-08  11.872826                0.015781
2    ales hemsky  2007-08  18.574099                0.073371
3   ales kotalik  2007-08  15.342405                0.045050
4  alex ovechkin  2007-08  23.101423                0.027567

In [48]:
# Join predictions to data
forwards_merged = data.merge(forwards_predictions, on=['PLAYER', 'SEASON', 'TOI/GP'], how='inner')
defence_merged = data.merge(defence_predictions, on=['PLAYER', 'SEASON', 'TOI/GP'], how='inner')

# Concatenate the two dataframes
final_data = pd.concat([forwards_merged, defence_merged])

In [49]:
final_data = final_data.sort_values(by=['SEASON', 'PLAYER']).reset_index(drop=True)
final_data.head(-10)[['PLAYER', 'SEASON', 'TEAM', 'PRED_SALARY_PERCENTAGE']]

                   PLAYER   SEASON      TEAM  PRED_SALARY_PERCENTAGE
0             adam burish  2007-08       chi                0.014010
1               adam hall  2007-08       pit                0.015781
2             ales hemsky  2007-08       edm                0.073371
3            ales kotalik  2007-08       buf                0.045050
4          alex goligoski  2007-08       pit                0.034137
...                   ...      ...       ...                     ...
12134        wyatt kaiser  2023-24       chi                0.027145
12135        yakov trenin  2023-24  col, nsh                0.026159
12136        yanni gourde  2023-24       sea                0.048688
12137     yegor chinakhov  2023-24       cbj                0.011167
12138  yegor sharangovich  2023-24       cgy                0.048007

[12139 rows x 4 columns]

In [50]:
# Create percentage of salary column
final_data['PRED/ACTUAL'] = final_data['PRED_SALARY_PERCENTAGE'] / final_data['SALARY CAP PERCENTAGE']

In [51]:
final_data['POSITION'].unique()

# Change the position column so that 'r' is 'Right Wing', 'l' is 'Left Wing', 'c' is 'Center', 'd' is 'Defence', 'c, l' is 'Center, Left Wing', 'c, r' is 'Center, Right Wing', 'l, r' is 'Left Wing, Right Wing'
final_data['POSITION'] = final_data['POSITION'].replace({'r': 'Right Wing', 'l': 'Left Wing', 'c': 'Center', 'd': 'Defence', 'c, l': 'Center, Left Wing', 'c, r': 'Center, Right Wing', 'l, r': 'Left Wing, Right Wing', 'd, l': 'Defence, Left Wing', 'd, r': 'Defence, Right Wing', 'd, c': 'Defence, Center'}) 

final_data['POSITION'].unique()

array(['Right Wing', 'Defence', 'Left Wing', 'Center, Left Wing',
       'Center', 'Left Wing, Right Wing', 'Center, Right Wing',
       'Defence, Left Wing'], dtype=object)

In [52]:
final_data['TEAM'].unique()

array(['chi', 'pit', 'edm', 'buf', 'wsh', 'van', 'nsh', 'tor', 'atl',
       'det', 'mtl', 'ott', 'bos', 'ana', 'car, chi', 'n.j', 'nyi',
       'ana, stl', 'l.a', 'dal', 'stl', 'chi, phi', 'min', 't.b',
       'dal, t.b', 'det, l.a', 'nyr', 'phi', 'fla', 'buf, s.j',
       'n.j, stl', 'nyr, stl', 's.j', 'atl, pit', 'cgy', 'cbj, edm',
       'phx', 'col', 'car', 'cbj', 'min, tor', 'pit, tor',
       'cgy, chi, phi', 'car, ott', 'col, fla', 'ana, nyi', 'van, wsh',
       'cbj, wsh', 'ana, bos', 'dal, min', 'buf, edm', 'stl, tor',
       'cbj, ott', 'dal, stl', 'nyi, pit', 'ana, dal', 'nyi, ott',
       'cbj, t.b', 'ana, pit', 'min, nyr', 'phi, phx', 'dal, pit',
       'nyr, phx', 'buf, tor', 'dal, mtl', 'ana, atl', 'car, edm',
       'mtl, phi', 'ana, chi', 'atl, cbj', 'car, t.b', 'car, l.a',
       'col, van', 'atl, mtl', 'cgy, phx', 'ana, van', 'fla, nsh',
       'fla, t.b', 'edm, l.a', 't.b, van', 'fla, phi, t.b', 'ana, s.j',
       'cgy, edm', 'ana, car', 'cgy, nyr', 'car, van', 'ana, chi, min',
       'min, mtl', 'car, wsh', 'bos, fla', 'chi, min', 'bos, min',
       'atl, buf', 'bos, buf', 'edm, nsh', 'bos, phx', 'fla, mtl',
       'det, t.b', 'cgy, nsh', 'min, wsh', 'ana, nyr', 'cbj, l.a',
       'cgy, tor', 'atl, n.j', 'ana, tor', 'l.a, t.b', 'car, tor',
       'nyr, s.j', 'col, phx', 'ana, mtl', 'phx, tor', 'ana, edm',
       'phi, t.b', 'nyi, t.b', 'car, s.j', 'ana, phx', 'buf, cbj',
       'car, col', 'det, phi', 'car, cgy', 'atl, s.j', 'atl, bos',
       'buf, stl', 'ana, cgy', 'car, fla', 'chi, ott', 'fla, van',
       'bos, ott', 'col, stl', 'n.j, wsh', 'fla, wsh', 'atl, cgy',
       'car, cgy, s.j', 'chi, fla', 'mtl, nyi', 'dal, n.j', 'ana, ott',
       'phi, tor', 'nsh, ott', 'bos, col', 'ana, mtl, van', 'atl, fla',
       'car, min', 'atl, nyi', 'cbj, phx', 'ana, car, fla', 'col, mtl',
       'col, wsh', 'col, edm', 'bos, tor', 'wpg', 'car, n.j', 'mtl, nsh',
       'ana, wpg', 'cgy, nyi', 'ott, t.b', 'bos, nyi', 'nsh, phx, pit',
       'buf, van', 'cbj, min', 'col, s.j', 'ott, phx', 's.j, t.b',
       'cbj, wpg', 'car, mtl', 'chi, wpg', 'cbj, stl', 'dal, fla',
       'ana, min, n.j', 'col, det', 'min, n.j', 'cbj, pit', 'cgy, mtl',
       'edm, min', 'dal, phi', 'fla, n.j', 'cbj, van', 'col, t.b',
       'edm, stl', 'fla, nyr', 'car, phi, t.b', 'n.j, wpg', 'cbj, cgy',
       'n.j, nsh', 'l.a, mtl', 'dal, van', 'cbj, nyr', 'pit, s.j',
       'pit, wpg', 's.j, tor', 'cgy, pit', 'cgy, stl', 'mtl, nyr',
       'edm, fla', 'car, pit', 'fla, l.a', 'bos, dal', 'nsh, wsh',
       'chi, s.j', 'edm, tor', 'fla, wpg', 'phx, s.j', 'buf, l.a',
       'col, tor', 'nsh, s.j', 'l.a, phi', 'n.j, phx', 'phi, van',
       'col, dal', 'car, nsh, pit', 'edm, ott', 'bos, phi', 'nyi, phi',
       'phx, wsh', 'buf, min', 'bos, edm', 'buf, ott', 'mtl, van',
       'l.a, nyr', 'det, nsh', 'chi, phx', 'ana, wsh', 'nsh, nyr',
       'cgy, dal', 'fla, pit', 'nyr, t.b', 'buf, min, nyi', 'chi, t.b',
       'edm, s.j', 'chi, nyi', 'mtl, nyr, van', 'col, phi',
       'buf, mtl, nyi', 'chi, van', 'ari', 'car, det', 'ari, chi',
       'ari, van', 'bos, t.b', 'buf, mtl', 'ari, nyr', 'nsh, tor',
       'ana, fla', 'ari, bos', 'cgy, wsh', 'cbj, tor', 'edm, pit',
       'ari, cgy, dal', 'buf, wpg', 'dal, det', 'pit, stl', 'ana, cbj',
       'dal, s.j', 'car, wpg', 'edm, mtl', 'cbj, chi', 'cbj, dal',
       'nyr, wpg', 'det, n.j', 'nsh, stl, tor', 'ana, cbj, mtl',
       'ari, edm, pit', 'fla, min', 'cbj, chi, tor', 'nyi, s.j',
       'ari, stl', 'edm, van', 'edm, wpg', 'ari, col', 'cbj, col',
       'n.j, pit', 'tor, wsh', 'ana, col', 'chi, l.a', 'ari, mtl',
       'ott, tor', 'chi, mtl', 'cgy, min', 'mtl, n.j', 'col, n.j',
       'car, nyr', 'cgy, van', 'det, fla', 'ana, buf', 'cgy, fla',
       'ana, ari, chi', 'bos, car', 'ari, cbj', 'bos, det', 'bos, n.j',
       'mtl, s.j', 'buf, wsh', 'chi, l.a, pit', 'cbj, nsh', 'ari, pit',
       'ari, nsh', 'chi, pit', 'ari, wpg', 'ott, van', 'det, tor',
       'nsh, stl', 'det, nyr', 't.b, tor', 'col, nsh', 'cgy, ott',
       'cbj, n.j', 'buf, nsh', 'bos, wpg', 's.j, van', 'chi, dal',
       'stl, wsh', 'phi, pit', 'ari, min', 'nyr, ott', 'ari, cgy',
       'mtl, t.b', 'ari, tor', 'n.j, nsh, van', 'fla, tor', 'ana, n.j',
       'det, mtl', 'edm, nyr', 'chi, det', 'ott, s.j', 'car, stl',
       'dal, nyr', 'vgk', 'edm, mtl, nyi', 'van, vgk', 'ott, pit',
       'l.a, ott', 'ana, t.b', 'mtl, wpg', 'ott, phi',
       'cbj, edm, l.a, van', 'bos, nyr', 'col, ott', 'n.j, nyr',
       'min, stl', 'edm, wsh', 'l.a, van', 'cgy, l.a, ott', 'edm, n.j',
       'stl, wpg', 'det, pit', 's.j, vgk', 'chi, nsh', 'pit, vgk',
       'buf, det, pit', 'ari, l.a', 'mtl, tor', 'det, vgk', 'bos, chi',
       'min, nsh', 'min, vgk', 'chi, edm', 'l.a, pit, wsh',
       'edm, fla, ott', 'col, fla, pit', 'pit, van', 'det, s.j',
       'l.a, tor', 'ari, mtl, phi', 'tor, van', 'det, wsh', 'ott, vgk',
       'min, wpg', 'ana, stl, van', 'fla, s.j', 'cgy, l.a', 'car, nsh',
       'nsh, phi', 'edm, nyr, van', 'l.a, pit, van', 'car, edm, vgk',
       'l.a, vgk', 'min, pit', 'det, edm', 'n.j, nyi', 'n.j, t.b',
       'cgy, s.j', 's.j, wsh', 'vgk, wsh', 'vgk, wpg', 'buf, pit',
       'ana, phi', 'ott, wpg', 'cgy, chi', 'det, stl', 'fla, ott',
       'ana, nsh', 'buf, mtl, stl', 'mtl, ott', 'mtl, vgk', 'tor, wpg',
       'ari, n.j', 'col, nyr, ott', 'buf, n.j', 'buf, fla', 'ari, buf',
       'col, min, s.j', 'col, min', 'bos, nsh', 'l.a, pit', 'van, wpg',
       'chi, vgk', 'phi, wsh', 'sea', 'sea, t.b', 'nyi, sea', 'fla, phi',
       'sea, tor', 'sea, wsh', 'edm, phi', 'sea, vgk', 'ari, wsh',
       'nyr, phi', 'bos, sea', 'sea, wpg', 'car, cbj', 'tor, vgk',
       'n.j, sea', 'ana, min', 'buf, vgk', 'ari, t.b, wpg', 'ari, s.j',
       'nyr, van', 'min, sea', 'buf, chi', 'chi, col', 'n.j, s.j',
       'nyi, van', 'nsh, t.b', 'bos, wsh', 'n.j, van', 'col, nyr, tor',
       'nsh, sea', 'det, van', 'bos, van', 'nyr, vgk', 'chi, tor',
       'ari, ott', 's.j, sea', 's.j, t.b, wpg', 'nsh, pit', 'ari, edm',
       'nsh, wpg', 'det, min', 'chi, nyr', 'nyi, tor', 'ari, car',
       't.b, wpg', 'bos, cbj', 'chi, nsh, van', 'buf, col', 'cgy, vgk',
       'min, s.j', 'nyr, pit', 'mtl, pit', 'buf, phi', 'ari, t.b',
       'fla, nyi', 'cgy, n.j', 'nyi, stl', 'l.a, nsh', 'col, sea',
       'min, t.b'], dtype=object)

In [53]:
team_mapping = {
    'ana': 'Anaheim Ducks',
    'ari': 'Arizona Coyotes',
    'atl': 'Atlanta Thrashers',  
    'bos': 'Boston Bruins',
    'buf': 'Buffalo Sabres',
    'cgy': 'Calgary Flames',
    'car': 'Carolina Hurricanes',
    'cbj': 'Columbus Blue Jackets',
    'chi': 'Chicago Blackhawks',
    'col': 'Colorado Avalanche',
    'dal': 'Dallas Stars',
    'det': 'Detroit Red Wings',
    'edm': 'Edmonton Oilers',
    'fla': 'Florida Panthers',
    'l.a': 'Los Angeles Kings',
    'min': 'Minnesota Wild',
    'mtl': 'Montreal Canadiens',
    'n.j': 'New Jersey Devils',
    'nsh': 'Nashville Predators',
    'nyi': 'New York Islanders',
    'nyr': 'New York Rangers',
    'ott': 'Ottawa Senators',
    'phi': 'Philadelphia Flyers',
    'phx': 'Phoenix Coyotes',  
    'pit': 'Pittsburgh Penguins',
    's.j': 'San Jose Sharks',
    'stl': 'St. Louis Blues',
    't.b': 'Tampa Bay Lightning',
    'tor': 'Toronto Maple Leafs',
    'van': 'Vancouver Canucks',
    'vgk': 'Vegas Golden Knights',
    'wpg': 'Winnipeg Jets',  
    'wsh': 'Washington Capitals',
    'sea': 'Seattle Kraken',
}

In [54]:
# Function to unabbreviate team names
def unabbreviate_teams(team_abbr):
    # Split the string by comma to account for multiple teams
    teams = team_abbr.split(', ')
    # Map each abbreviation to its full name using the team_mapping
    full_names = [team_mapping.get(team.strip(), "Unknown") for team in teams]
    # Join the full names back into a string separated by commas
    return ', '.join(full_names)

In [55]:
final_data['TEAM_FULL_NAMES'] = final_data['TEAM'].apply(unabbreviate_teams)

In [56]:
# Save the data
outpath_dir = '../../Data/Warehouse/FrontEnd/'
outpath_file = 'front_end_data.csv'

if not os.path.exists(outpath_dir):
    os.makedirs(outpath_dir)

final_data.to_csv(outpath_dir + outpath_file, index=False)